PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX cpo: <http://example.com/cpo#>
PREFIX slowmo: <http://example.com/slowmo#>

SELECT ?candi ?path ?precond
FROM <http://localhost:3030/ds/spek>
FROM <http://localhost:3030/ds/seeps>

WHERE {
  ?candi a cpo:cpo_0000053 .
  ?path a cpo:cpo_0000029 .

  ?path slowmo:HasPrecondition ?precond .
  ?candi obo:RO_0000091|slowmo:uses_intervention_property ?prop .

  FILTER(?precond = ?prop)
}
